// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CadastrarUsuario(arg1:model.UsuarioCadastrado):Promise<string>;
